// Package artifact is the library for files that flow through
// conversations: user uploads, files generated by coding clients, exported
// transcripts, and workspace snapshot ZIPs.
//
// Two artifact kinds:
//
//   - file: content is copied into a content-addressed store (CAS) keyed
//     by SHA-256, so identical content is stored once no matter how many
//     artifact records point at it.
//   - link: for very large trees (e.g. a big local git repo) the library
//     stores a reference — the local path plus an optional remote URL
//     (GitHub/Gitea) as an archival fallback in case the local copy is
//     deleted after checkin — instead of copying content.
//
// Layout under the library root:
//
//	index/<id>.json      one metadata record per artifact
//	cas/<aa>/<sha256>    content blobs (aa = first two hex chars)
package artifact

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"mime"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

// Kind distinguishes stored content from references.
type Kind string

const (
	KindFile Kind = "file"
	KindLink Kind = "link"
)

// ErrNotFound is returned for unknown artifact IDs.
var ErrNotFound = errors.New("artifact: not found")

// Artifact is one record in the library.
type Artifact struct {
	ID        string    `json:"id"`
	Kind      Kind      `json:"kind"`
	Name      string    `json:"name"`
	MediaType string    `json:"media_type,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// File-kind fields.
	Size   int64  `json:"size,omitempty"`
	SHA256 string `json:"sha256,omitempty"`

	// Link-kind fields.
	LocalPath string `json:"local_path,omitempty"`
	RemoteURL string `json:"remote_url,omitempty"`

	// Provenance (all optional).
	ConversationID string `json:"conversation_id,omitempty"`
	TurnID         string `json:"turn_id,omitempty"`
	Origin         string `json:"origin,omitempty"` // e.g. "user-upload", "client-output", "export"
	Note           string `json:"note,omitempty"`
}

// Meta is the optional provenance attached when adding an artifact.
type Meta struct {
	ConversationID string
	TurnID         string
	Origin         string
	Note           string
}

// Library stores artifacts under a root directory.
type Library struct {
	root string
	mu   sync.Mutex
	now  func() time.Time
}

// NewLibrary creates (if needed) and opens a library rooted at dir.
func NewLibrary(dir string) (*Library, error) {
	for _, sub := range []string{"index", "cas"} {
		if err := os.MkdirAll(filepath.Join(dir, sub), 0o755); err != nil {
			return nil, fmt.Errorf("artifact: init %s: %w", dir, err)
		}
	}
	return &Library{root: dir, now: time.Now}, nil
}

// Root returns the library's root directory.
func (l *Library) Root() string { return l.root }

// AddFile stores content from r as a new file artifact named name.
// Identical content deduplicates in the CAS; the metadata record is always
// new. The reader is consumed fully.
func (l *Library) AddFile(ctx context.Context, name string, r io.Reader, meta Meta) (*Artifact, error) {
	l.mu.Lock()
	defer l.mu.Unlock()

	// Stream to a temp file while hashing, then move into place.
	tmp, err := os.CreateTemp(filepath.Join(l.root, "cas"), "incoming-*")
	if err != nil {
		return nil, err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath) // no-op after successful rename

	h := sha256.New()
	size, err := io.Copy(io.MultiWriter(tmp, h), r)
	closeErr := tmp.Close()
	if err != nil {
		return nil, fmt.Errorf("artifact: reading content: %w", err)
	}
	if closeErr != nil {
		return nil, closeErr
	}
	sum := hex.EncodeToString(h.Sum(nil))

	blob := l.blobPath(sum)
	if _, err := os.Stat(blob); errors.Is(err, os.ErrNotExist) {
		if err := os.MkdirAll(filepath.Dir(blob), 0o755); err != nil {
			return nil, err
		}
		if err := os.Rename(tmpPath, blob); err != nil {
			return nil, err
		}
	}

	a := l.newRecord(KindFile, name, meta)
	a.Size = size
	a.SHA256 = sum
	if err := l.writeRecord(a); err != nil {
		return nil, err
	}
	return a, nil
}

// AddFileFromPath stores the file at path (basename becomes the artifact
// name unless name overrides it).
func (l *Library) AddFileFromPath(ctx context.Context, path, name string, meta Meta) (*Artifact, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	if name == "" {
		name = filepath.Base(path)
	}
	return l.AddFile(ctx, name, f, meta)
}

// AddLink stores a reference artifact: a local path (e.g. a large git
// repo) plus an optional remote URL kept as an archival fallback.
func (l *Library) AddLink(ctx context.Context, name, localPath, remoteURL string, meta Meta) (*Artifact, error) {
	l.mu.Lock()
	defer l.mu.Unlock()

	if localPath == "" && remoteURL == "" {
		return nil, fmt.Errorf("artifact: link needs a local path or a remote URL")
	}
	if localPath != "" {
		abs, err := filepath.Abs(localPath)
		if err != nil {
			return nil, err
		}
		localPath = abs
	}
	if name == "" {
		name = filepath.Base(localPath)
	}
	a := l.newRecord(KindLink, name, meta)
	a.LocalPath = localPath
	a.RemoteURL = remoteURL
	if err := l.writeRecord(a); err != nil {
		return nil, err
	}
	return a, nil
}

// Get returns an artifact record by ID.
func (l *Library) Get(ctx context.Context, id string) (*Artifact, error) {
	return l.readRecord(id)
}

// Open returns the content of a file artifact, or — for a link whose local
// path still exists — the linked file. A dangling link returns an error
// that mentions the remote fallback URL when one is recorded.
func (l *Library) Open(ctx context.Context, id string) (io.ReadCloser, error) {
	a, err := l.readRecord(id)
	if err != nil {
		return nil, err
	}
	switch a.Kind {
	case KindFile:
		return os.Open(l.blobPath(a.SHA256))
	case KindLink:
		f, err := os.Open(a.LocalPath)
		if err != nil {
			if a.RemoteURL != "" {
				return nil, fmt.Errorf("artifact: local copy %q unavailable (%v); remote fallback: %s",
					a.LocalPath, err, a.RemoteURL)
			}
			return nil, fmt.Errorf("artifact: local copy %q unavailable: %w", a.LocalPath, err)
		}
		return f, nil
	default:
		return nil, fmt.Errorf("artifact: unknown kind %q", a.Kind)
	}
}

// BlobPath returns the on-disk path of a file artifact's content (useful
// for zero-copy export). Errors for link artifacts.
func (l *Library) BlobPath(ctx context.Context, id string) (string, error) {
	a, err := l.readRecord(id)
	if err != nil {
		return "", err
	}
	if a.Kind != KindFile {
		return "", fmt.Errorf("artifact: %s is a %s, not stored content", id, a.Kind)
	}
	return l.blobPath(a.SHA256), nil
}

// List returns all artifacts, newest first. If conversationID is non-empty
// only that conversation's artifacts are returned.
func (l *Library) List(ctx context.Context, conversationID string) ([]*Artifact, error) {
	entries, err := os.ReadDir(filepath.Join(l.root, "index"))
	if err != nil {
		return nil, err
	}
	var out []*Artifact
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		a, err := l.readRecord(strings.TrimSuffix(e.Name(), ".json"))
		if err != nil {
			continue // skip damaged records rather than failing the list
		}
		if conversationID != "" && a.ConversationID != conversationID {
			continue
		}
		out = append(out, a)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].CreatedAt.Equal(out[j].CreatedAt) {
			return out[i].ID > out[j].ID
		}
		return out[i].CreatedAt.After(out[j].CreatedAt)
	})
	return out, nil
}

// ExportRecord returns the raw index-record bytes for an artifact, for
// byte-identical round trips through export bundles.
func (l *Library) ExportRecord(ctx context.Context, id string) ([]byte, error) {
	b, err := os.ReadFile(l.recordPath(id))
	if errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("%w: %q", ErrNotFound, id)
	}
	return b, err
}

// RestoreRecord re-creates an artifact from raw index-record bytes (as
// produced by ExportRecord). If a record with the same ID already exists
// it is left untouched (content is identical by construction) and false
// is returned. For file-kind artifacts blob supplies the content, which
// must hash to the record's SHA-256; it may be nil when the blob is
// already in the CAS (records sharing content dedupe naturally).
func (l *Library) RestoreRecord(ctx context.Context, raw []byte, blob io.Reader) (*Artifact, bool, error) {
	var a Artifact
	if err := unmarshal(raw, &a); err != nil {
		return nil, false, fmt.Errorf("artifact: restore: parsing record: %w", err)
	}
	if a.ID == "" || strings.ContainsAny(a.ID, "/\\") {
		return nil, false, fmt.Errorf("artifact: restore: invalid record id %q", a.ID)
	}
	if a.Kind != KindFile && a.Kind != KindLink {
		return nil, false, fmt.Errorf("artifact: restore: unknown kind %q", a.Kind)
	}
	if a.Kind == KindFile && a.SHA256 == "" {
		return nil, false, fmt.Errorf("artifact: restore: file record %q has no sha256", a.ID)
	}

	l.mu.Lock()
	defer l.mu.Unlock()

	if _, err := os.Stat(l.recordPath(a.ID)); err == nil {
		return &a, false, nil
	}

	if a.Kind == KindFile {
		if _, err := os.Stat(l.blobPath(a.SHA256)); errors.Is(err, os.ErrNotExist) {
			if blob == nil {
				return nil, false, fmt.Errorf("artifact: restore: %q needs blob %s but none was supplied", a.ID, a.SHA256)
			}
			tmp, err := os.CreateTemp(filepath.Join(l.root, "cas"), "incoming-*")
			if err != nil {
				return nil, false, err
			}
			tmpPath := tmp.Name()
			defer os.Remove(tmpPath)
			h := sha256.New()
			if _, err := io.Copy(io.MultiWriter(tmp, h), blob); err != nil {
				tmp.Close()
				return nil, false, fmt.Errorf("artifact: restore: reading blob: %w", err)
			}
			if err := tmp.Close(); err != nil {
				return nil, false, err
			}
			if sum := hex.EncodeToString(h.Sum(nil)); sum != a.SHA256 {
				return nil, false, fmt.Errorf("artifact: restore: blob for %q hashes to %s, record says %s", a.ID, sum, a.SHA256)
			}
			dst := l.blobPath(a.SHA256)
			if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
				return nil, false, err
			}
			if err := os.Rename(tmpPath, dst); err != nil {
				return nil, false, err
			}
		}
	}

	// Write the raw bytes verbatim so the restored record is
	// byte-identical to the exported one.
	tmp := l.recordPath(a.ID) + ".tmp"
	if err := os.WriteFile(tmp, raw, 0o644); err != nil {
		return nil, false, err
	}
	if err := os.Rename(tmp, l.recordPath(a.ID)); err != nil {
		return nil, false, err
	}
	return &a, true, nil
}

// Orphans lists artifacts tied to conversations that no longer exist:
// records whose non-empty ConversationID is rejected by exists. Records
// with no conversation are global and never orphans. Deleting a
// conversation deliberately keeps its artifacts (they may be shared or
// exported); this is the deferred cleanup path — pair with Delete,
// which garbage-collects CAS blobs when their last record goes.
func (l *Library) Orphans(ctx context.Context, exists func(convID string) bool) ([]*Artifact, error) {
	all, err := l.List(ctx, "")
	if err != nil {
		return nil, err
	}
	var out []*Artifact
	for _, a := range all {
		if a.ConversationID != "" && !exists(a.ConversationID) {
			out = append(out, a)
		}
	}
	return out, nil
}

// Delete removes an artifact record. A file blob is garbage-collected when
// no remaining record references its hash.
func (l *Library) Delete(ctx context.Context, id string) error {
	l.mu.Lock()
	defer l.mu.Unlock()

	a, err := l.readRecord(id)
	if err != nil {
		return err
	}
	if err := os.Remove(l.recordPath(id)); err != nil {
		return err
	}
	if a.Kind != KindFile {
		return nil
	}
	// GC: any other record still using this blob?
	others, err := l.List(ctx, "")
	if err != nil {
		return err
	}
	for _, o := range others {
		if o.Kind == KindFile && o.SHA256 == a.SHA256 {
			return nil
		}
	}
	if err := os.Remove(l.blobPath(a.SHA256)); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

// --- internals ---

func (l *Library) newRecord(kind Kind, name string, meta Meta) *Artifact {
	now := l.now().UTC()
	var suffix [4]byte
	if _, err := rand.Read(suffix[:]); err != nil {
		panic(fmt.Sprintf("artifact: rand: %v", err))
	}
	return &Artifact{
		ID:             now.Format("20060102T150405") + "-" + hex.EncodeToString(suffix[:]),
		Kind:           kind,
		Name:           name,
		MediaType:      mime.TypeByExtension(strings.ToLower(filepath.Ext(name))),
		CreatedAt:      now,
		ConversationID: meta.ConversationID,
		TurnID:         meta.TurnID,
		Origin:         meta.Origin,
		Note:           meta.Note,
	}
}

func (l *Library) blobPath(sum string) string {
	return filepath.Join(l.root, "cas", sum[:2], sum)
}

func (l *Library) recordPath(id string) string {
	return filepath.Join(l.root, "index", id+".json")
}

func (l *Library) writeRecord(a *Artifact) error {
	b, err := marshalIndent(a)
	if err != nil {
		return err
	}
	tmp := l.recordPath(a.ID) + ".tmp"
	if err := os.WriteFile(tmp, b, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, l.recordPath(a.ID))
}

func (l *Library) readRecord(id string) (*Artifact, error) {
	b, err := os.ReadFile(l.recordPath(id))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, fmt.Errorf("%w: %q", ErrNotFound, id)
		}
		return nil, err
	}
	var a Artifact
	if err := unmarshal(b, &a); err != nil {
		return nil, err
	}
	return &a, nil
}
